site_name: Lunar Tear Installation Guide

theme:
  name: material
  logo: images/icon.webp
  favicon: images/icon.webp

  palette:
    - scheme: slate
      primary: black
      accent: white

  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - content.code.copy

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Android Tools and Tailscale: android-tools-and-tailscale.md
  - Recommended Emulators: recommended-emulators.md
  - Known Issues: known-issues.md
  - Updating: updating.md
  - Video Resources: video.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
